In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.impute import SimpleImputer

In [43]:
df=pd.read_csv("C:\\Users\\ASUS\Documents\\Machine learning\\Dataset\\data preproccesing example.csv")

In [44]:
df.head()

city   age   salary e for be
0   Mumbai  27.0  51000.0      yes
1  Newyork  27.0  48000.0      yes
2   Mumbai  30.0  52000.0       no
3  Newyork   NaN  60000.0       no
4   Tokeyo  48.0      NaN      yes

In [45]:
df.info

<bound method DataFrame.info of          city   age   salary e for be
0      Mumbai  27.0  51000.0      yes
1     Newyork  27.0  48000.0      yes
2      Mumbai  30.0  52000.0       no
3     Newyork   NaN  60000.0       no
4      Tokeyo  48.0      NaN      yes
5      Tokeyo   NaN  51000.0       no
6   Singapore  33.0  60000.0       no
7     Newyork  40.0  70000.0      yes
8      Mumbai  38.0      NaN      yes
9   Singapore  25.0  30000.0       no
10     Tokeyo   NaN  50000.0       no
11  Singapore  33.0  49000.0       no
12    Newyork  40.0  72000.0      yes
13     Mumbai  31.0  79000.0      yes
14  Singapore  37.0  85000.0       no>

# Independent and dependent variable

In [46]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
print(x)
print(y)

[['Mumbai' 27.0 51000.0]
 ['Newyork' 27.0 48000.0]
 ['Mumbai' 30.0 52000.0]
 ['Newyork' nan 60000.0]
 ['Tokeyo' 48.0 nan]
 ['Tokeyo' nan 51000.0]
 ['Singapore' 33.0 60000.0]
 ['Newyork' 40.0 70000.0]
 ['Mumbai' 38.0 nan]
 ['Singapore' 25.0 30000.0]
 ['Tokeyo' nan 50000.0]
 ['Singapore' 33.0 49000.0]
 ['Newyork' 40.0 72000.0]
 ['Mumbai' 31.0 79000.0]
 ['Singapore' 37.0 85000.0]]
['yes' 'yes' 'no' 'no' 'yes' 'no' 'no' 'yes' 'yes' 'no' 'no' 'no' 'yes'
 'yes' 'no']


# Handle missing values

In [47]:
df.isnull().sum()

city        0
age         3
salary      2
e for be    0
dtype: int64

In [48]:
# df.dropna(inplace=True)

In [53]:
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
print(x)

[['Mumbai' 27.0 51000.0]
 ['Newyork' 27.0 48000.0]
 ['Mumbai' 30.0 52000.0]
 ['Newyork' 34.083333333333336 60000.0]
 ['Tokeyo' 48.0 58230.769230769234]
 ['Tokeyo' 34.083333333333336 51000.0]
 ['Singapore' 33.0 60000.0]
 ['Newyork' 40.0 70000.0]
 ['Mumbai' 38.0 58230.769230769234]
 ['Singapore' 25.0 30000.0]
 ['Tokeyo' 34.083333333333336 50000.0]
 ['Singapore' 33.0 49000.0]
 ['Newyork' 40.0 72000.0]
 ['Mumbai' 31.0 79000.0]
 ['Singapore' 37.0 85000.0]]


# Data Encoding

In [55]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# OneHotEncoder

In [62]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
x

array([[0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 27.0, 51000.0],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 30.0, 52000.0],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 34.083333333333336, 60000.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 48.0, 58230.769230769234],
       [1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 34.083333333333336, 51000.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 33.0, 60000.0],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 40.0, 70000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 38.0, 58230.769230769234],
       [1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 25.0, 30000.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 34.083333333333336, 50000.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 33.0, 49000.0],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 40.0, 72000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 31.0, 79000.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 37.0, 85000.0]], dtype=object)

# Label Encoder

In [63]:
from sklearn.preprocessing import LabelEncoder

In [68]:
le=LabelEncoder()
y=le.fit_transform(y)
y

array([1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0])

# Split the dataset for training and testing

In [69]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)

In [71]:
x_train

array([[1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 34.083333333333336, 50000.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 48.0, 58230.769230769234],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 31.0, 79000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 27.0, 51000.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 37.0, 85000.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 25.0, 30000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 38.0, 58230.769230769234],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 40.0, 72000.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 33.0, 49000.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 34.083333333333336, 51000.0]],
      dtype=object)

In [72]:
x_test

array([[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 34.083333333333336, 60000.0],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 40.0, 70000.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 33.0, 60000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 30.0, 52000.0]], dtype=object)

In [73]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0])

In [74]:
y_test

array([0, 1, 0, 0])

# Feature Scaling

In [75]:
from sklearn.preprocessing import StandardScaler

In [78]:
scaler=StandardScaler()
x_train[:,4:]=scaler.fit_transform(x_train[:,4:])
x_train

array([[1.0, 0.0, 1.0, 0.0, -0.4714045207910318, -0.6123724356957945,
        1.632993161855452, 0.010707595557084039, -0.49229409150564374],
       [1.0, 0.0, 1.0, 0.0, -0.4714045207910318, -0.6123724356957945,
        1.632993161855452, 2.1962468220418416, 0.054854299147937866],
       [1.0, 0.0, 1.0, 0.0, 2.121320343559643, -0.6123724356957945,
        -0.6123724356957945, -1.1016926095399489, -0.6252460368981028],
       [0.0, 1.0, 0.0, 1.0, -0.4714045207910318, -0.6123724356957945,
        -0.6123724356957945, -0.47351367019103635, 1.435509116685012],
       [0.0, 1.0, 0.0, 1.0, -0.4714045207910318, -0.6123724356957945,
        -0.6123724356957945, -1.1016926095399489, -0.4258181188094142],
       [1.0, 0.0, 1.0, 0.0, -0.4714045207910318, 1.632993161855452,
        -0.6123724356957945, 0.4687547388323323, 1.834364952862389],
       [1.0, 0.0, 1.0, 0.0, -0.4714045207910318, 1.632993161855452,
        -0.6123724356957945, -1.415782079214405, -1.821813545430234],
       [0.0, 1.0, 0.

In [79]:
x_test[:,4:]=scaler.fit_transform(x_test[:,4:])
x_test

array([[1.0, 0.0, 1.0, 0.0, 1.0, -0.5773502691896258, 0.0,
        -0.05164998142274846, -0.07832604499879574],
       [1.0, 0.0, 1.0, 0.0, 1.0, -0.5773502691896258, 0.0,
        1.5781938768062023, 1.488194854977119],
       [1.0, 0.0, 1.0, 0.0, -1.0, 1.7320508075688774, 0.0,
        -0.3500720963097402, -0.07832604499879574],
       [0.0, 1.0, 0.0, 1.0, -1.0, -0.5773502691896258, 0.0,
        -1.1764717990737155, -1.3315427649795275]], dtype=object)

# Outlier