# Mathmatic operation in numpy

In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,17).reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
arr2=np.arange(16,32).reshape(4,4)
arr2

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [4]:
arr1+arr2

array([[17, 19, 21, 23],
       [25, 27, 29, 31],
       [33, 35, 37, 39],
       [41, 43, 45, 47]])

In [5]:
np.add(arr1,arr2)

array([[17, 19, 21, 23],
       [25, 27, 29, 31],
       [33, 35, 37, 39],
       [41, 43, 45, 47]])

In [6]:
arr2-arr1

array([[15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15]])

In [7]:
np.subtract(arr2,arr1)

array([[15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15]])

In [8]:
arr1/arr2

array([[0.0625    , 0.11764706, 0.16666667, 0.21052632],
       [0.25      , 0.28571429, 0.31818182, 0.34782609],
       [0.375     , 0.4       , 0.42307692, 0.44444444],
       [0.46428571, 0.48275862, 0.5       , 0.51612903]])

In [9]:
np.divide(arr2,arr1)

array([[16.        ,  8.5       ,  6.        ,  4.75      ],
       [ 4.        ,  3.5       ,  3.14285714,  2.875     ],
       [ 2.66666667,  2.5       ,  2.36363636,  2.25      ],
       [ 2.15384615,  2.07142857,  2.        ,  1.9375    ]])

In [10]:
arr3=arr1*arr2
arr3

array([[ 16,  34,  54,  76],
       [100, 126, 154, 184],
       [216, 250, 286, 324],
       [364, 406, 450, 496]])

In [11]:
arr4=np.multiply(arr1,arr2)
arr4

array([[ 16,  34,  54,  76],
       [100, 126, 154, 184],
       [216, 250, 286, 324],
       [364, 406, 450, 496]])

In [12]:
arr1 @ arr2

array([[ 240,  250,  260,  270],
       [ 592,  618,  644,  670],
       [ 944,  986, 1028, 1070],
       [1296, 1354, 1412, 1470]])

In [13]:
arr1.dot(arr2)

array([[ 240,  250,  260,  270],
       [ 592,  618,  644,  670],
       [ 944,  986, 1028, 1070],
       [1296, 1354, 1412, 1470]])

In [14]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
arr1.max()

16

In [16]:
arr2.max()

31

In [17]:
arr1.min()

1

In [18]:
arr2.min()

16

In [19]:
arr1.max(axis=0)

array([13, 14, 15, 16])

In [20]:
arr1.max(axis=1)

array([ 4,  8, 12, 16])

In [21]:
arr1.argmax()

15

In [22]:
arr1.argmin()

0

In [23]:
arr1.sum()

136

In [24]:
arr1.sum(axis=0)

array([28, 32, 36, 40])

In [25]:
arr1.sum(axis=1)

array([10, 26, 42, 58])

In [26]:
np.mean(arr1)

8.5

In [27]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        ]])

In [28]:
np.std(arr1)

4.6097722286464435

In [29]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05],
       [4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06]])

In [30]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665],
       [2.56494936, 2.63905733, 2.7080502 , 2.77258872]])

In [31]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999],
       [0.95424251, 1.        , 1.04139269, 1.07918125],
       [1.11394335, 1.14612804, 1.17609126, 1.20411998]])