# Numpy Random Function()

In [2]:
import numpy as np 
import random

In [3]:
np.random.random(1)

array([0.59255508])

In [4]:
np.random.random(20)

array([0.88563252, 0.53380419, 0.75834202, 0.57772729, 0.27647485,
       0.0787102 , 0.01532051, 0.41903762, 0.32756196, 0.80022685,
       0.33949833, 0.77280211, 0.08195805, 0.41159299, 0.82036565,
       0.9346452 , 0.1000608 , 0.63264925, 0.56186892, 0.95585282])

In [5]:
np.random.random((4,4))

array([[0.08944132, 0.34720888, 0.06543408, 0.25793768],
       [0.1849515 , 0.78715062, 0.88922382, 0.89348547],
       [0.75103311, 0.9781553 , 0.99168679, 0.70785012],
       [0.06415013, 0.05555442, 0.43391   , 0.74777184]])

In [6]:
np.random.randint(1,4,(4,4))

array([[2, 2, 3, 3],
       [2, 2, 3, 1],
       [2, 3, 1, 1],
       [2, 3, 3, 2]])

In [7]:
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 2],
        [2, 1, 2, 1],
        [2, 1, 1, 3],
        [1, 2, 3, 2]],

       [[1, 3, 3, 2],
        [2, 2, 3, 2],
        [3, 1, 1, 2],
        [3, 2, 2, 2]]])

In [11]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [12]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [13]:
np.random.seed(8)
np.random.randint(1,4,(2,4,4))

array([[[1, 2, 2, 2],
        [3, 1, 1, 1],
        [2, 2, 1, 2],
        [3, 1, 2, 2]],

       [[2, 2, 3, 3],
        [3, 3, 2, 1],
        [2, 1, 2, 2],
        [3, 2, 3, 3]]])

In [15]:
np.random.rand(3)

array([0.98287055, 0.12785571, 0.32213079])

In [16]:
np.random.rand(3,3)

array([[0.07094284, 0.22476994, 0.39363491],
       [0.896145  , 0.34546161, 0.98474944],
       [0.02873205, 0.35168474, 0.38095889]])

In [17]:
x=[1,2,3,4]
np.random.choice(x)

4

In [18]:
x=[1,2,3,4]
np.random.choice(x)

2

In [20]:
for i in range(10):
    print(np.random.choice(x))

4
1
2
4
3
3
3
3
3
4


In [22]:
np.random.permutation(x)

array([1, 2, 4, 3])

In [24]:
np.random.permutation(x)

array([3, 2, 1, 4])

In [25]:
np.random.permutation(x)

array([1, 2, 4, 3])

In [26]:
np.random.permutation(x)

array([2, 1, 4, 3])